export const NOTIFICATION_TYPE = {
  // --- Customer notifications ---
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_REMINDER: "BOOKING_REMINDER",
  SERVICE_CHANGE_ACCEPTED: "SERVICE_CHANGE_ACCEPTED",
  SERVICE_CHANGE_REJECTED: "SERVICE_CHANGE_REJECTED",
  REVIEW_REQUEST: "REVIEW_REQUEST",
  PROMOTION: "PROMOTION",

  // --- Barber notifications ---
  NEW_BOOKING_REQUEST: "NEW_BOOKING_REQUEST",
  BOOKING_MODIFICATION_REQUEST: "BOOKING_MODIFICATION_REQUEST", // reschedule request from customer
  SERVICE_CHANGE_REQUESTED: "SERVICE_CHANGE_REQUESTED", // customer wants to change services
  BOOKING_CANCELLED_BY_CUSTOMER: "BOOKING_CANCELLED_BY_CUSTOMER",
  NEW_CUSTOMER_REVIEW: "NEW_CUSTOMER_REVIEW",

  // --- Admin notifications ---
  BARBER_REQUEST_SUBMITTED: "BARBER_REQUEST_SUBMITTED",
  BARBER_REQUEST_APPROVED: "BARBER_REQUEST_APPROVED",
  BARBER_REQUEST_REJECTED: "BARBER_REQUEST_REJECTED",
  NEW_CONTACT_MESSAGE: "NEW_CONTACT_MESSAGE",
} as const;

/** @deprecated Use NOTIFICATION_TYPE */
export const NOTIFICATION_TYPES = NOTIFICATION_TYPE;
