/** Master service catalog — used by booking, barber services, walk-ins. */
export const SERVICE_CATALOG = [
  {
    id: "signature-cut",
    name: "Signature Cut",
    price: 45,
    duration: 45,
    description: "Consultation, precision cut, hot towel finish.",
    popular: true,
  },
  {
    id: "skin-fade",
    name: "Skin Fade",
    price: 40,
    duration: 40,
    description: "Tight gradient fade with razor detail work.",
    popular: true,
  },
  {
    id: "beard-sculpt",
    name: "Beard Sculpt",
    price: 28,
    duration: 25,
    description: "Trim, shape and conditioning oil treatment.",
    popular: false,
  },
  {
    id: "hot-towel-shave",
    name: "Hot Towel Shave",
    price: 35,
    duration: 30,
    description: "Classic straight-razor shave with hot towel.",
    popular: false,
  },
  {
    id: "father-son",
    name: "Father & Son Cut",
    price: 65,
    duration: 60,
    description: "Two precision cuts, side by side.",
    popular: false,
  },
  {
    id: "the-works",
    name: "The Works",
    price: 85,
    duration: 75,
    description: "Cut + shave + beard + scalp treatment.",
    popular: true,
  },
];
